on:
    pull_request:

env:
    NUSHELL_CARGO_PROFILE: ci
    NU_LOG_LEVEL: DEBUG

jobs:
    nu-check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: "Fetch main branch"
              run: |
                  git fetch origin main --depth 1
            - uses: hustcer/setup-nu@v3.9
              with:
                  version: "*"
                  check-latest: true
                  # features: full # dataframe and extra included
            - name: toolkit check pr
              shell: nu {0}
              # nix STUB_IDE_CHECK when nushell/nushell#12208 fixed
              run: |
                  use ${{ github.workspace }}/toolkit.nu *
                  STUB_IDE_CHECK=true check pr --and-exit
